name: Dima Droubi
favicon: null
layout_spectrum: 0.3823
typography_spectrum: 0.587105697253719
title: Dima Droubi - Romancière
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1e1e'
    - '#b2161d'
    - '#ffffff'
    - '#b45342'
    - '#b5b5b5'
  brandStrength: 0.08929882105439901
  lightness: 0.8408852641005069
  saturation: 0.44976691971533
  rhythmicContrast: 0.567519250093028
purpose: []
