name: Dima Droubi
favicon: null
layout_spectrum: 0.24611
typography_spectrum: 0.7254760218784213
title: La Sultane du Caire - de Dima Droubi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#B2161D'
    - '#A4463E'
    - '#BABEA5'
  brandStrength: 0.2865670083556324
  lightness: 0.8774465194437653
  saturation: 0.3473892936017364
  rhythmicContrast: 0.5314960449468344
purpose: []
